### ISSUE TITLE
kube-proxy pods shows below compliance items

### ISSUE THREAD

**Issue by singhnix** [aws/aws-eks-best-practices#179]
Is your idea request related to a problem that you've solved? Please describe.

When running a third party security scanning tool on EKS, it shows below compliance items for kube-proxy pods.

Describe the best practice
NA

Describe alternatives you've considered
NA

Additional context

Following EKS security best practices "Pod security" for kube-proxy pods "https://aws.github.io/aws-eks-best-practices/security/docs/pods/". I am aware that, if these compliance items are handled, then the kube-proxy pods will stop working.

Reported Compliance items for cloudwatch pods.

image: 602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/kube-proxy:v1.21.2-eksbuild.2

(CIS_Docker_v1.3.1   - 5.9) Do not share the host's network namespace
--
(CIS_Docker_v1.3.1 - 5.12) Mount   container's root filesystem as read only
(CIS_Docker_v1.3.1 - 5.20) Do not share   the host's UTS namespace
(CIS_Docker_v1.3.1 - 5.21) Do not disable   default seccomp profile
(CIS_Docker_v1.3.1 - 5.25) Restrict   container from acquiring additional privileges
(CIS_Docker_v1.3.1 - 5.28) Use PIDs   cgroup limit
(CIS_Docker_v1.3.1 - 5.10) Limit memory   usage for container
Container is running as root
(CIS_Docker_v1.3.1 - 5.4) Do not use   privileged containers

**Comment by jicowan** [comment]
@singhnix Some pods have to run as privileged and/or root, e.g. kube-proxy because it modifies iptables. If you're concerned about this, there are CNIs like Cilium, that don't rely on kube-proxy. As I mentioned in another issue you filed, you should enforce strict security policies in specific namespaces and lighter security policies in others that require pods to run with elevated privileges like kube-system.
