### ISSUE TITLE
Using SSM for managed nodes.

### ISSUE THREAD

**Issue by tapuhi** [aws/aws-eks-best-practices#5]
In https://aws.github.io/aws-eks-best-practices/hosts/ it's mentioned that it is better to use SSM session manager rather than ssh access to the nodes. 

Is there a way to get SSM installed on managed EKS nodes? By default the ssm agent is NOT installed.

**Comment by jicowan** [comment]
@tapuhi, thanks for the feedback.  You could add the SSM agent to the EKS Optimized AMI.  We have a set of [Packer scripts](https://github.com/awslabs/amazon-eks-ami) that you can use to do this.  Would it be useful to include an example?  We are also close to publishing a blog post that will describe how to run the SSM agent as a daemonset.  Hopefully this will make things a little easier.  I also learned about a feature earlier today called EC2 instance connect which is yet another way to connect to your instance.  Ideally, you want to avoid using SSH keys because they are static and are too easily shared.

**Comment by tapuhi** [comment]
As far as I understand EKS optimized AMIs are not supported with managed nodes. Please correct me if I am wrong.

**Comment by jicowan** [comment]
Not yet, but soon. In the interim you can run a daemonset that’s runs a script to install the  SSM agent or you can run the SSM agent as a daemonset. As I mentioned in my earlier response, we will be publishing a blog about that shortly. Would it be useful to have an example that shows how to run a shell script as a daemonset?

**Comment by tapuhi** [comment]
Yes please.

**Comment by tapuhi** [comment]
And also explain/send a example on how to run the SSM agent as daemonset. 
THanks!

**Comment by jicowan** [comment]
@tapuhi Please review this https://github.com/jicowan/ssm-agent-daemonset/blob/master/README.md when you have a moment.  If it meets your requirements, I will integrate it into the guidance.  Thanks!

**Comment by tapuhi** [comment]
Thanks!  @jicowan  it did the job and now I can see the nodes in SSM
